name: Secret Detection in PR

on:
  pull_request:
    paths:
      - '**/*' # Include all file changes in the PR

jobs:
  secret-detection:
    name: Secret Detection
    runs-on: ubuntu-latest

    steps:
    # Checkout the code of the repository where the workflow is running
    - name: Checkout PR Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install required tools (e.g., grep, sed, etc.)
    - name: Install Tools
      run: sudo apt-get update && sudo apt-get install -y grep

    # Extract modified files in the PR
    - name: List Modified Files
      id: list-files
      run: |
        git diff --name-only origin/main > modified_files.txt
        cat modified_files.txt

    # Scan code using regex patterns from the repository
    - name: Scan for Secrets
      run: |
        exit_code=0
        regex_file="secrets-regex.txt"
        
        if [[ ! -f $regex_file ]]; then
          echo "Regex file not found: $regex_file"
          exit 1
        fi

        while IFS= read -r file; do
          if [[ -f $file ]]; then
            while IFS= read -r regex; do
              grep -En "$regex" "$file" && exit_code=1 || true
            done < $regex_file
          fi
        done < modified_files.txt
        exit $exit_code

    # Notify about the results
    - name: Annotate Results
      if: failure()
      run: echo "Potential secrets detected. Please review the logs."
