name: Check for Hardcoded Secrets

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  secret-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run secret scan
      run: |
        # Define regex patterns for common secrets
        regex_patterns=(
          'AKIA[0-9A-Z]{16}'  # AWS Access Key ID
          'aws_secret_access_key\s*=\s*[A-Za-z0-9/+=]{40}'  # AWS Secret Access Key
          '-----BEGIN PRIVATE KEY-----'  # Private Key
          '-----BEGIN RSA PRIVATE KEY-----'  # RSA Private Key
          'password\s*=\s*.*'  # Generic password pattern
        )

        # Scan for secrets in the codebase
        for pattern in "${regex_patterns[@]}"; do
          if grep -r -E "$pattern" .; then
            echo "Error: Hardcoded secret detected!"
            exit 1
          fi
        done

        echo "No hardcoded secrets found."
