name: Secret Scanning

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  detect-secrets:
    name: Detect-Secrets Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Detect-Secrets
        run: pip install detect-secrets

      - name: Run Detect-Secrets
        run: detect-secrets scan > .secrets.baseline
